# Generated by Django 2.2.19 on 2021-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="testperm",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
